#[file name]: render.yaml
services:
  - type: web
    name: yitio-bot
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PORT
        value: 10000
      - key: BOT_TOKEN
        sync: false
      - key: PROVIDER_TOKEN
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: ADMIN_TOKEN
        sync: false
      - key: WEBHOOK_SECRET_TOKEN
        value: YOUR_WEBHOOK_SECRET_HERE  # Add this line
      - key: RENDER_EXTERNAL_URL
        value: https://y-i-t-i-o.onrender.com
    autoDeploy: true
    healthCheckPath: /health
